### ISSUE TITLE
Do we need ag-grid-community

### ISSUE THREAD

**Issue by JordanSjodinFaithlife** [Faithlife/styled-ui#102]
I added the packages listed [here](https://github.com/Faithlife/styled-ui/blame/master/catalog/grid/documentation.md#L4), but was having issues until I also added `ag-grid-community`.

Is `ag-grid-community` also required and should be listed there? Or is something wrong with my setup that required me to have `ag-grid-community`?

CC @dustinsoftware

**Comment by JordanSjodinFaithlife** [comment]
I assume this is due to me not having an enterprise license set up. Perhaps this should be addressed here?

**Comment by dustinsoftware** [comment]
Per [this medium post](https://medium.com/ag-grid/introducing-version-19-of-ag-grid-a7fc97714843) it looks like just a rename. We should update the styled-ui docs to reference the new package name.

**Comment by korbinancell** [comment]
Closing this because this is addressed in v6 beta. If you have any other questions feel free to ask here https://github.com/Faithlife/styled-ui/issues/216
