### ISSUE TITLE
Migrate to styled components v4

### ISSUE THREAD

**Issue by dustinsoftware** [Faithlife/styled-ui#111]
I'd like to get this done before we release 5.0.

[v4 blog post](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112)

Things we need to migrate:
- component.extend has been removed. Use `styled(component)` instead
- Remove all uses of `innerRef`, delete `forwardRef` wrappers
 
Current PR is #75

**Comment by awesomebob** [comment]
Resolved in #75
