### ISSUE TITLE
Add complex reusable components to styled-ui vs create a new project

### ISSUE THREAD

**Issue by korbinancell** [Faithlife/styled-ui#131]
### 1 
> One of the stated goals for this project is to include [_simple_ UI components](https://github.com/Faithlife/styled-ui#goals). At what point would we consider a component "complex" enough to split into a separate project? I would consider the `GroupSelector` component in this category as well. @bryanrsmith what do you think?

 - [awesomebob](https://github.com/Faithlife/styled-ui/pull/129#issuecomment-462824207)

### 2
> I'm a little unsure about this as well. I asked the same question, and my impression was that it hadn't been answered because it hadn't come up. I'm inclined to say that so long as the component has a separate output bundle and is generally applicable to a wide range of Faithlife projects I don't see any harm in putting it here. Separate repos for medium-sized components has management overhead that I'd rather avoid paying until there's a good reason.
>
>Some things that I'd say should probably not live in this repo:
>
>* Things that are only applicable to a specific subset of projects within the organization.
>* Things that have large or many dependencies that aren't shared with the rest of the components in this library, or aren't widely used by projects with the organization. Things that have large dependencies that are likely to change (e.g., flavor-of-the-month rich text libraries).
>* Things that are likely to require frequent breaking changes.

- [bryansmith](https://github.com/Faithlife/styled-ui/pull/129#issuecomment-462878856)

### 3
>There is certainly _some_ overhead, although a large part of that will be reduced as we move to embrace Sheepdog.
>
>I would be in favor of at least setting up one new package for complex shared components, and maybe that repo wouldn't need to be on public GitHub as the implementation is that much more Faithlife-specific.
>
>To maybe expand a little on our stated goals in the README, `styled-ui` gives us the official UI building blocks that teams need to implement new specs in their various projects. The proposed new `shared-complex-components` would be for complex components that aren't themselves building blocks, they are completely-implemented components that can be re-used across projects.

 - [awesomebob](https://github.com/Faithlife/styled-ui/pull/129#issuecomment-462885043)

### 4
> > I would be in favor of at least setting up one new package for complex shared components
>
> For what purpose? What benefits do you anticipate?

 - [bryansmith](https://github.com/Faithlife/styled-ui/pull/129#issuecomment-462971514)

### 5
>I guess my main questions are:
>
> 1. How do we define what a "simple" component is?
> 2. To what extent is it a worthwhile goal for this project to have only "simple" UI components?

 - [awesombob](https://github.com/Faithlife/styled-ui/pull/129#issuecomment-463278614)

**Comment by korbinancell** [comment]
@awesomebob @bryanrsmith 
I moved everything here make it a little easier to parse so you are not dodging code review as well

If I may throw my hat in the ring, I think that we should limit styled-ui to something that conceivably every one of our react projects could make use of. Then for the larger ones a private `shared-complex-components` or even individual projects for each would make sense.

There is some precedent for many individual plugins to let you pick only what you want in your project (Babel 7 and its proposal plugins), and with Sheepdog to keep everything in order the individual projects might not be so bad.

**Comment by bryanrsmith** [comment]
Can anyone articulate the advantages of splitting the repo? I don't understand the goal there. If a component is too complex for this repo, I'd say it needs *its own* repo. A second shared component repo seems like it would just add work, to me.

> To what extent is it a worthwhile goal for this project to have only "simple" UI components?

I can guess, but (like @awesomebob) I don't really know what this means, or how we'd define the boundary. I'm unsure of the reasoning behind that goal. It seems unrelated to the other listed goals, and the current state of the repo is already in violation of it.

> with Sheepdog to keep everything in order

I probably don't understand the project, but in what way does Sheepdog reduce management overhead? It's basically Greenkeeper, right? In my experience, Greenkeeper doesn't reduce management over head at all. It simply makes you aware of the need to perform management tasks.

**Comment by bryanrsmith** [comment]
Thanks for moving the discussion to an issue @korbinancell!

**Comment by awesomebob** [comment]
> Can anyone articulate the advantages of splitting the repo? I don't understand the goal there.

My goal is to help define what belongs in this repo.

I'm open to considering other ways to narrow that down, but was suggesting that splitting the repo would be one way in which to help define that. It's certainly not the only way, and may well not be the best way.

> If a component is too complex for this repo, I'd say it needs _its own_ repo.

I can get on board with that.

> In what way does Sheepdog reduce management overhead? It's basically Greenkeeper, right?

I haven't used Greenkeeper, but from what I'm reading it looks like Sheepdog handles a part of that functionality. Sheepdog opens PRs to bump the version numbers in all downstream projects for a repo, anything that depends on the npm package.

**Comment by RobertBolender** [comment]
[FaithlifeEquipment](https://git.faithlife.dev/Logos/FaithlifeEquipment) now exists as a shared repo for complex components designed for Faithlife Equip projects.
