### ISSUE TITLE
[RFD] Accordion / Collapsible Section

### ISSUE THREAD

**Issue by RobertBolender** [Faithlife/styled-ui#144]
# Accordions (or CollapsibleSection)

* Specifically describe the problem you'd like the new component to solve:

Design has a common pattern of separating groups of controls into separate collapsible sections.
Sometimes these sections can be toggled open or closed with a click.
Other times these sections should be controlled by another component, such as these Toggles. (See proposal here: https://github.com/Faithlife/styled-ui/issues/145)

* Are there existing solutions or examples where this component would help?

Here are examples of the open/closed states, both with and without the Toggles:

![accordion-1](https://user-images.githubusercontent.com/3677807/54454482-cb77f600-4716-11e9-9887-a5b5455a2a2a.png)
![accordion-2](https://user-images.githubusercontent.com/3677807/54454483-cc108c80-4716-11e9-9093-c44da9469eb9.png)
![accordion-3](https://user-images.githubusercontent.com/3677807/54454486-ce72e680-4716-11e9-9c11-f32c80c90c70.png)
![accordion-4](https://user-images.githubusercontent.com/3677807/54454488-ce72e680-4716-11e9-908b-3f145e56edba.png)

* Describe the proposed API:

The Accordion would use a fully controlled pattern. Internally the Accordion can use the existing `Collapse` component.

* Are there existing specs or designs?

[Yes.](https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/5b9bfe0f73b5c068de1b3eff)

* Do you have additional questions?

No.

**Comment by korbinancell** [comment]
LGTM

**Comment by bryanrsmith** [comment]
This sounds like 2 proposals. Can we split them?

**Comment by bryanrsmith** [comment]
It'd be great to include a complete description of the API of the components, maybe as an example consumer. The accordion sounds like it would require at least two sets of elements per section (the header, and the collapsible body). Is this really an accordion, where only one section may be open at a time? Or is it a collapsible section?

Seems like the toggle button has some localizable text. How should that be handled?

**Comment by awesomebob** [comment]
> This sounds like 2 proposals. Can we split them?

Here is the new split proposal for the Toggle component:
https://github.com/Faithlife/styled-ui/issues/145

**Comment by awesomebob** [comment]
> Is this really an accordion, where only one section may be open at a time? Or is it a collapsible section?

Great questions. My intention (which I didn't fully describe at first) is in fact much closer to a "CollapsibleSection" than an "Accordion". Each section would be its own component, and if a consumer actually wants "accordion" functionality with only one section open at a time, they can handle that state themselves. I don't think we need to mandate that functionality at the library level.

**Comment by korbinancell** [comment]
Closed along with https://github.com/Faithlife/styled-ui/pull/157 being merged
