### ISSUE TITLE
[RFD] Toggle

### ISSUE THREAD

**Issue by RobertBolender** [Faithlife/styled-ui#145]
# Toggle

* Specifically describe the problem you'd like the new component to solve:

A very simple "yes/no" component that represents a binary choice that is functionally similar to a checkbox.

* Are there existing solutions or examples where this component would help?

This component is currently used on Faithlife.com.

![accordion-1](https://user-images.githubusercontent.com/3677807/54550740-dd050c00-4969-11e9-9c66-8b0000fc58cd.png)
![accordion-2](https://user-images.githubusercontent.com/3677807/54550741-dd050c00-4969-11e9-8e57-9de589a200aa.png)

* Describe the proposed API:

Fully controlled component with props:
```
static propTypes = {
  value: PropTypes.bool,
  onToggle: PropTypes.func
}
```

* Are there existing specs or designs?

[Zeplin spec here](https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/59ee876e4582a457c39dbefe)

* Do you have additional questions?

How should we handle localization in Styled-UI components? (Asked by @bryanrsmith)

**Comment by korbinancell** [comment]
Reactstrap allows you to pass in localization as a prop. Perhaps styled-ui can add a localization-through-context component and have any components that require localization come with a consumer.

**Comment by bryanrsmith** [comment]
A lot of projects here use `@faithlife/react-ui`'s localization component, which isn't on public github. Shared components generally accept a `localizedResources` prop in the top-level component, and then use the localization helpers within the component as needed.

**Comment by awesomebob** [comment]
> A lot of projects here use `@faithlife/react-ui`'s localization component, which isn't on public github. Shared components generally accept a `localizedResources` prop in the top-level component, and then use the localization helpers within the component as needed.

If it's not on public GitHub, are we able to use it within this project at all?

**Comment by bryanrsmith** [comment]
The travis build couldn't install it, since it's not in the public npm registry. We have a similar (but different) problem with the publish target for this project.

**Comment by bryanrsmith** [comment]
We have specs for three variants of this. The Yes/No variant shown in this issue has unresolved design questions regarding localization-- its size is unable to accommodate certain translations.

I've implemented the two other variants: switch and binary choice. https://faithlife.github.io/styled-ui/#/Switch/variations

Note that I've gone with the more commonly-used ["switch"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role) terminology rather than "toggle".

**Comment by korbinancell** [comment]
@RobertBolender Looks like we have a switch component shipped. Looks like we are still missing localization support for YES | NO toggles? Is this still the case?

**Comment by RobertBolender** [comment]
My understanding is that we deferred it until we had a better understanding of how we wanted to handle localization in Styled-UI, I don't think we have *any* localization yet here, do we?
