### ISSUE TITLE
[RFD] Tabs

### ISSUE THREAD

**Issue by korbinancell** [Faithlife/styled-ui#152]
# Tabs https://github.com/Faithlife/styled-ui/pull/151

https://deploy-preview-151--faithlife-styled-ui.netlify.com/#/tabs/variations

* Specifically describe the problem you'd like the new component to solve:

Specs for a tab handler component exist as well as implementations in Giving and soon to be amber picker.

* Are there existing solutions or examples where this component would help?

See above.

* Describe the proposed API:

Should be fully uncontrolled. Theme can be changed. The body of the components would be wrapped in a `Tab` component
ex: 
![image](https://user-images.githubusercontent.com/14059089/56002262-8fcd3f00-5c76-11e9-9a34-0e4f017564e3.png)

* Are there existing specs or designs?

https://app.zeplin.io/project/594ad63bfedba903192b9a4f/screen/59f8ff290101883312d0271b

* Do you have additional questions?

Do we need to handle tabs being added and removed after initial render?
Can we assume that tabs will always be registered in the order they are mounted?
Currently all components are always rendered, just not shown. Should components be unmounted when not shown (or should we offer the option)?

**Comment by bryanrsmith** [comment]
I'm a little concerned about the rigidity of this API. It's common to render tabs in a different area of the UI than the panels. We'll definitely need to render arbitrary elements as tab names. A fully-uncontrolled API also makes it likely that we'll be forced to introduce imperative handles later for things like changing the selected tab.

https://ui.reach.tech/tabs is pretty good tabs implementation. Perhaps we should consider wrapping it, or borrowing from its API design?
