### ISSUE TITLE
Split button

### ISSUE THREAD

**Issue by rmjohnson** [Faithlife/styled-ui#174]
https://app.zeplin.io/project/5b10273d413156335e1b6743/screen/5cc227bb6f17562d6da75beb

![image](https://user-images.githubusercontent.com/249152/59314243-51013880-8c69-11e9-9bfb-7f7080daeac2.png)

I'm not sure if "split button" is the correct name for this component or not. Basically the button on the right will have a `Popover` and the part on the left is some text showing the state that is hidden in the popover.

I figured I should ask here first to see if this is something that should be in styled-ui but just hasn't been written yet or if I should create a one off for my use case.

**Comment by bryanrsmith** [comment]
Interesting. I don't recall ever seeing this particular pattern before. A similar pattern I see more frequently is a split where the left is a button, and the right is a button that triggers a selection dropdown that changes the mode of the left button.
![image](https://user-images.githubusercontent.com/186704/59369877-345f1200-8cf6-11e9-9954-3d56670ec41d.png)


It seems like we could extend our existing button implementation to support joining buttons together stylistically, perhaps with a wrapper that could orchestrate the style variants required in the participating buttons.

In your case, it kinda seems like the whole thing could just be a single button. It's probably worth asking Amber for an opinion.

**Comment by rmjohnson** [comment]
@bryanrsmith, just to keep you updated, Jake decided to remove the calendar icon and make it just a normal button with the text. Thanks for the additional context!
