### ISSUE TITLE
Dropdown is trapped by `overflow: hidden`

### ISSUE THREAD

**Issue by kbsletten** [Faithlife/styled-ui#177]
I don't know what the 100% solution is, but I've seen success with allowing a React portal to specify a mount position outside of the problematic DOM element. This has been a problem when using ag-grid as there's a lot of difficulty with elements overlapping multiple cells.

**Comment by korbinancell** [comment]
It looks like you've opened a couple pr's with fixes, is this still an issue you are having?

**Comment by kbsletten** [comment]
This was resolved by a change to the popover manager.
