### ISSUE TITLE
[RFD] Export Kebab

### ISSUE THREAD

**Issue by timothy-b** [Faithlife/styled-ui#190]
# Kebab 🍢 

* **Specifically describe the problem you'd like the new component to solve:**

I need a kebab, but there isn't one here, so I'll probably just reuse the one that exists in my project instead.

* **Are there existing solutions or examples where this component would help?**

Existing solutions:

https://github.com/Faithlife/styled-ui/blob/612330bcc71ec322563ccff473d954e31be183f4/catalog/grid/member-directory.jsx#L34

See also the `VerticalKebabPopup` component in our Faithlife repo.

* **Describe the proposed API:**

🤷‍♂ I'd either copy the `VerticalKebabPopup` into this repo, or export the above component and massage it to meet my use-case.

* **Are there existing specs or designs?**

Probably, but I don't know where they'd live.

* **Do you have additional questions?**

Are you on board with this? I could start working on it right now.

**Comment by korbinancell** [comment]
Using svgr to create and export a collection of common icon components would be pretty cool.

**Comment by bryanrsmith** [comment]
Is this something other than a dropdown with a specific icon button? It kinda seems like something that doesn't need a dedicated component.

**Comment by korbinancell** [comment]
Closing because of icons are now exported https://faithlife.github.io/styled-ui/#/icons
