### ISSUE TITLE
DatePeriodPicker should allow tokens on datePeriods

### ISSUE THREAD

**Issue by rmjohnson** [Faithlife/styled-ui#199]
Currently when consuming `DatePeriodPicker`, if you want to pass in `datePeriods`, and then respect the correct `displayName` when `setSelectedDate`, you have to do a lookup on the `start` and `end` dates passed into `setSelectedDate`. e.g.
```js
let newDatePeriod: IDatePeriod = Object.values(datePeriods).find(
	dp =>
		(dateFunctions.isSameDay(dateRange.start, dp.dateRange.start) &&
			dateFunctions.isSameDay(dateRange.end, dp.dateRange.end)) ||
		(dateRange.start === dp.dateRange.start && dateRange.end === dp.dateRange.end)
);
```
It would be nice if instead the callback function when a date period is picked passed back a token that so we could instead do something like:
```js
let newDatePeriod: IDatePeriod = datePeriods[datePeriodToken];
```

This wouldn't catch the "didn't select a date period but happened to be the same date range selected as a date period" case (that I'm catching above with the `isSameDay` check) but that feels like an acceptable trade off.

[Original discussion that prompted this](https://git.faithlife.dev/Logos/ChurchManagement/pull/35/files#r139854)

**Comment by rmjohnson** [comment]
Actually..maybe it makes more sense to return the entire `datePeriod` (i.e. including the display name) as opposed to just the `dateRange`. The whole point of doing that `find` is just to get at the display name.

**Comment by bryanrsmith** [comment]
Sounds reasonable. PRs welcome.
