### ISSUE TITLE
Grid v2 v1

### ISSUE THREAD

**Issue by korbinancell** [Faithlife/styled-ui#216]
# This has moved to [FaithlifeEquipment](https://git.faithlife.dev/Logos/FaithlifeEquipment/issues/61)

~A common thread to keep track of questions/issues with the new ag-grid wrapper. Feel free to leave a comment or question and I will add it to the list of things to do.~

~Spec from amber: https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/5d56f9a48847a29b54627e3c~

~## Tasks~

- [x]  Rename from Table -> Grid to facilitate adding a simple styled table component in the future.
- [x]  Allow passing a max height directly.
- [x]  Investigate sizeColumnsToFit() does not seem to fire on initial page load in safari.
- [x] Update to spec from amber
- [x] Add simpler way to add props to `BaseGrid` without having to update every grid comp.
- [ ] Export to csv context menu does not work with custom components.
- [ ] Handle server-side row model `SimpleGrid` and `PaginatedGrid`
- [x] Add drag-n-drop to `SimpleGrid`
- [x] Add checkbox support to all grids.
- [ ] Improve no rows found message.
- [ ] Cell editing not supported in TreeGrid.
- [ ] Server side paging
- [ ] Fix "No Row To Show" casing

~## Possible/ As Needed~

- [ ] Switch to svg icons
- [ ] Allow printing mode for client-side row model

**Comment by ronnywoods** [comment]
`sizeColumnsToFit()` does not seem to fire on initial page load in safari.  ref: https://www.flowdock.com/app/logos/fl-comms/threads/lbTgyVKp5yo8o6gPKeKlREZLhJR

**Comment by ronnywoods** [comment]
Just submitted a PR to fix the `sizeColumnsToFit()` issue: https://github.com/Faithlife/styled-ui/pull/218

**Comment by ronnywoods** [comment]
Submitted another PR exposing `maxHeight` and `minHeight`: https://github.com/Faithlife/styled-ui/pull/221

Rationale included in PR description/comments

**Comment by TaitWeicht** [comment]
@korbinancell I noticed that `gridOptions` is [here](https://github.com/Faithlife/styled-ui/blob/vnext/components/grid/base-table.jsx#L23) in the base table, but in the [simple table](https://github.com/Faithlife/styled-ui/blob/vnext/components/grid/simple-table.jsx#L5) there is no way to way to pass `gridOptions` in.
Reason being I'd really like to pass in a [getRowHeight callback](https://www.ag-grid.com/javascript-grid-row-height/) to give my grid data variable row heights depending on content. Not sure if this is the way to do it?

**Comment by TaitWeicht** [comment]
There appears to be a bug where grid rows don't render correctly when data in the grid has changed. 
[AGgridRenderingBug.mov.zip](https://github.com/Faithlife/styled-ui/files/3517827/AGgridRenderingBug.mov.zip)

**Comment by ronnywoods** [comment]
@korbinancell sorry to keep hitting you up one-off like this...testing on iOS uncovered some bugs.  I just submitted a PR that ensures column state changes occur in the correct order (that is, we need to ensure the reset to column state occurs _before_ the necessary updates to column state.  See https://github.com/Faithlife/styled-ui/pull/229 .  It may have a minor conflict with my other open PR...let me know if / when you merge the other open PR and I can quickly resolve conflict.

Also note there may be a similar problem happening with row height causing the issues @TaitWeicht  mentions above.  I'll dig in quickly there and potentially submit a separate PR for the rowHeight issue.

**Comment by korbinancell** [comment]
Most issues are solved in https://github.com/Faithlife/styled-ui/pull/249

**Comment by rmjohnson** [comment]
I wanted to use a `groupByColumn` and also have it expanded it by default. I was able to accomplish this by using:
```
gridOptions={{
    groupDefaultExpanded: 1,
}}
```
but I figured this functionality should probably be built into `SimpleGrid` / `BaseGrid`.

**Comment by korbinancell** [comment]
https://github.com/Faithlife/styled-ui/issues/282

**Comment by korbinancell** [comment]
Use https://git.faithlife.dev/Logos/FaithlifeEquipment/issues/61 from now on
