### ISSUE TITLE
Add style overrides for menu-checkbox component

### ISSUE THREAD

**Issue by lawrencesin** [Faithlife/styled-ui#217]
We have a [design spec](https://www.flowdock.com/app/logos/ui-ux-dsgnhavn/threads/iYebvKfrVzawIa0QZ1pHl7sVuao) from the UIUX team where we utilize the Dropdown with checkboxes like in the [Dropdown Menu Items](https://faithlife.github.io/styled-ui/#/dropdown/variations?a=dropdown-menu-items) example but we need it styled in a certain way for the UI on FaithlifeTV.com.

I was hitting a wall utilizing the themes/styleOverrides but was unable to get the component to look like how we need it in the design spec.  I would like to add some style overrides for the menu-checkbox component and to override the `backgroundColor` for the checkboxes and the corresponding `hover backgroundColor` to allow us to achieve our goal.

Here is the [corresponding flow](https://www.flowdock.com/app/logos/styled-ui/threads/AuR77Z9vaQw6qGeGDDN7wOfg0n6).

**Comment by korbinancell** [comment]
This is available to change currently with the new theming options, but will be even better supported in https://github.com/Faithlife/styled-ui/pull/379

Feel free to re-open if this doesn't suit your needs.
