### ISSUE TITLE
HelpBox needs to support alignment with buttons

### ISSUE THREAD

**Issue by ELanning** [Faithlife/styled-ui#242]
![image](https://user-images.githubusercontent.com/38930062/65722364-fb5a6b80-e060-11e9-8fad-80614588af74.png)

As you can see, the text is not aligned with the button. Some CSS could be used to align it with the button, but then it would _not_ be aligned with the yellow warning icon.

**Comment by bryanrsmith** [comment]
I don't think I understand the request. Can you provide a code sample that reproduces the problem, and describe the desired result?

The demos for this component do not exhibit this issue. It looks like that screenshot is using a larger button, or adding some extra space around the button, or both. Is that deliberate?

**Comment by ELanning** [comment]
![image](https://user-images.githubusercontent.com/38930062/65905393-52b84e80-e375-11e9-8b53-55fcbbb562bf.png)

I don't believe I'm adding any extra space?

Desired look:
![image](https://user-images.githubusercontent.com/38930062/65905439-65328800-e375-11e9-8150-fe3b5f813c06.png)

Code sample-
https://git.faithlife.dev/Logos/CommunicationsApi/blob/master/frontend/packages/communications-ui/components/edit-communication/index.tsx#L844
