### ISSUE TITLE
Product Drawer renders partially offscreen some viewports (SITES-5828)

### ISSUE THREAD

**Issue by kevinforrestkeyes** [Faithlife/styled-ui#244]
https://faithlife.atlassian.net/browse/SITES-5828

Product Drawer overflows on viewports under 990px before switching to mobile layout. To fix, I'm going to reposition the product drawer on affected viewport range.

**Comment by RobertBolender** [comment]
It looks like this was resolved in this Skeletor PR: https://git.faithlife.dev/Logos/Skeletor/pull/1823

If that is not the case, please feel free to re-open this issue.
