### ISSUE TITLE
ProductDrawer's dropdown either missing or broken when consumed as a module

### ISSUE THREAD

**Issue by tobs1701** [Faithlife/styled-ui#258]
In consuming the [product-drawer into Faithlife's brand-bar UI](https://git.faithlife.dev/Logos/brand-bar/compare/master...TobySteele:add_product_drawer) as a node module, I ran into the following problems:

1. Webpack doesn't include the `product-drawer-dropdown` into the `product-drawer` output, chunking it into a separate, numbered file instead. While the module knows that it needs this chunked file, the consumer is unaware of it and does not include it at runtime.
2. `product-drawer-dropdown` relies on `handleBlur` being defined in the current execution context; however, when the drawer is opened, that context is undefined and breaks the entire component.

I found a couple of workarounds to these issues, but I'm not sure I'm going in the right direction:

1. [Adding `webpackMode: eager`](https://github.com/Faithlife/styled-ui/compare/master...tobs1701:consumerify_product_drawer#diff-ce911b3965a75c0e02e79b4a94cb0c02R7) to the dropdown import ensures its inclusion into `product-drawer.js`; however, I don't like that this seems to undermine the bandwidth savings that chunking provides.
2. [Passing `handleBlur` into the component](https://github.com/Faithlife/styled-ui/compare/master...tobs1701:consumerify_product_drawer#diff-1bc2c4ceccf9a57afc04d3902e04993cR29-R31) side-steps the need for having a defined execution context.

I'm new to Webpack and relatively new to react, so would appreciate some guidance to better solutions if they exist.

**Comment by bryanrsmith** [comment]
1. I'm not sure what you mean by "the consumer is unaware of it and does not include it at runtime". Can you provide more info about the problem you're seeing? The dynamic import serves to reduce the size of the initial script bundle; eagerly loading it would retain the deferred execution benefit, but eliminate the primary benefit of reduced payload size.

2. Seems like a legit bug to me, and your change looks good. I'm happy to merge that.

**Comment by tobs1701** [comment]
> Can you provide more info about the problem you're seeing?

While running the brand-bar demo site locally, trying to open the product drawer results in the following console error:

![image](https://user-images.githubusercontent.com/2482021/67044855-05acda00-f0e2-11e9-9813-a747524e5c9a.png)

Opening the sources tab and examining the webpack output shows the following under @faithlife:

![image](https://user-images.githubusercontent.com/2482021/67044970-3b51c300-f0e2-11e9-8ef0-9eb09f9f723e.png)

Whereas if you look in the brand-bar project's `node_modules` folder, the file we want is clearly visible:

![image](https://user-images.githubusercontent.com/2482021/67045127-8966c680-f0e2-11e9-9caa-76c4a63b6061.png)

My interpretation is that because the dropdown is lazy-loaded into the drawer, the brand-bar doesn't know it's necessary when the webpack dev server is run, so the `7.js` chunk is never fetched.

Not sure if there's a way to update the [consumer webpack config](https://git.faithlife.dev/Logos/brand-bar/blob/997f0bcf743989451d5aceb718f2f18449a4cc20/webpack.config.js) to handle this.

**Comment by tobs1701** [comment]
As best as I can tell, I'm importing ProductDrawer correctly: https://git.faithlife.dev/Logos/brand-bar/pull/19/files#diff-84982dfe714fa0ceceac08047958e2d7R14

**Comment by RobertBolender** [comment]
I'm closing this issue because I think that PR #259 resolved it. If this is not the case, please feel free to reopen the issue.
