### ISSUE TITLE
[RFD] Update to modals

### ISSUE THREAD

**Issue by RobertBolender** [Faithlife/styled-ui#265]
# Modals

We already have a Modal component, but have received new specs for updated spacing and layout: https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/5da8b786136c341856fc8020

* Describe the proposed API changes:
We currently expose a ModalContent component that is a Box with default padding on all four sides. Amber has requested that the vertical padding between the ModalHeader and ModalContent, as well as the vertical padding between the ModalContent and ModalFooter not be arbitrarily configurable, it will either be 24px or 16px depending on the variant chosen.

The updated ModalContent Box will default to 0 vertical padding, and default to horizontal padding that matches the Modal's 24px/16px variant.

**Comment by bryanrsmith** [comment]
Are you proposing a change to the defaults, or constraining possible values for those props, or both?

**Comment by RobertBolender** [comment]
My initial thought was to just change the defaults.
Would you be in favor of not allowing the `padding` prop on the ModalContent box? I could add a separate "fullWidthContent` prop that would set the horizontal padding to 0, otherwise use the inherited padding from the Modal variant.

**Comment by bryanrsmith** [comment]
👍 No, I'd prefer to keep the API more open. Additional props and/or additional exports that make the happy defaults more easily accessible sound reasonable.
