### ISSUE TITLE
Establish guidelines for using stable but not yet widely available APIs in library code

### ISSUE THREAD

**Issue by bryanrsmith** [Faithlife/styled-ui#278]
Teams seem to frequently struggle with how to handle polyfills in library code. I think styled-ui can set the standard for this, and document the process for deciding which APIs are acceptable to use in library code, and how to handle (or not) polyfills. This may ultimately be more appropriate as a coding guideline.

**Comment by RobertBolender** [comment]
This issue has not generated any discussion over the past year. If you have any concrete proposals we'd be happy to look at them, either here or in the context of an internal coding guideline.
