### ISSUE TITLE
Override toggle text styles in Product Drawer.

### ISSUE THREAD

**Issue by tobs1701** [Faithlife/styled-ui#280]
Recent consumption of the ProductDrawer as part of https://faithlife.atlassian.net/browse/SITES-5126 has revealed the need to override the toggle text styling, specifically:

- text font
- text size
- text color

The goal here is to allow more consistent styling between the Drawer toggle and its consumer. The following doc provides more details: https://docs.google.com/document/d/1fUT08im_Q866O4WC-gCwD8Nw4NoGsMcODKiIGXCFm6s/edit

**Comment by RobertBolender** [comment]
It appears that this issue was resolved by PR #281. If that is not the case, please feel free to re-open this issue.
