### ISSUE TITLE
Use of GridColumn's hasInteractableElement Results in Console Warnings

### ISSUE THREAD

**Issue by JeremyEinfeld** [Faithlife/styled-ui#282]
If the `hasInteractableElement` attribute is set on the GridColumn component, this warning is logged to the console: `ag-grid: invalid colDef property 'hasInteractableElement' did you mean any of these: cellRendererSelector,enableCellChangeFlash,enablePivot,cellEditorSelector,enableRowGroup,editable,sortable,resizable`

**Comment by korbinancell** [comment]
Thanks for the report. I have an open pr with several fixes like this. I'll add it in.

**Comment by korbinancell** [comment]
This was solved in https://github.com/Faithlife/styled-ui/pull/293
Should ship with the next version of styled-ui.

**Comment by korbinancell** [comment]
v5.29.1 was merged to fl
