### ISSUE TITLE
[RFD] Usage of ResizeObserver

### ISSUE THREAD

**Issue by PatrickNausha** [Faithlife/styled-ui#303]
It appears consumers of some components are supposed to know they must polyfill `ResizeObserver` for Safari, IE (not supported by styled-ui?), and Edge. Is there some way to make this a little more obvious? I couldn't find a standard solution to this problem except that some frontend-focused npm packages will list in their docs which newer DOM APIs they use.

https://github.com/Faithlife/styled-ui/blob/a4f9655d95c321a4f8c0b035eb4371a888f6c3da/components/shared-hooks/useElementSize.js#L11

Is ResizeObserver even stable? From https://drafts.csswg.org/resize-observer-1/:

> This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress.

**Comment by bryanrsmith** [comment]
See https://github.com/Faithlife/styled-ui/pull/302

I've added a note to the documentation for components that use `ResizeObserver`.
