### ISSUE TITLE
Issue with ParameterInputBox within a Radio button

### ISSUE THREAD

**Issue by Nolan-Stidham** [Faithlife/styled-ui#365]
When using `ParameterSentences` in a radio button list, the border on the `ParameterInputBox` is too high:
![image](https://user-images.githubusercontent.com/71294656/93143098-1a9c3f80-f69c-11ea-9b7c-9a01af460255.png)

To fix this, I propose adding a styleOverride that allows developers to set the height of the `InputContainer` independently of the font size.

**Comment by RobertBolender** [comment]
This appears to be resolved by #366, if that is not the case please feel free to re-open this issue.
