### ISSUE TITLE
[BUG] Cannot override styles on disabled button.

### ISSUE THREAD

**Issue by PatrickNausha** [Faithlife/styled-ui#382]
**Describe the bug**
The v6 `Button` does not let me override the disabled styles with styled-system props.

**Actual Behavior**

```
<Button
	disabled
	size="small"
	icon={<Checkmark color="#62bb46" />}
	backgroundColor="green1"
	color="foregroundPrimary"
	border="none"
>
	{localization.registered}
</Button>
```
The above markup produces a button that looks like this:
![Screen Shot 2020-11-10 at 10 39 16 AM](https://user-images.githubusercontent.com/3759629/98716779-fded5280-2340-11eb-91c5-2692386b73f4.png)

**Expected behavior**

I would instead expect the button to look like the following.
![Screen Shot 2020-11-10 at 10 37 39 AM](https://user-images.githubusercontent.com/3759629/98716719-e746fb80-2340-11eb-93ae-a220489ddac0.png)

**Additional context**
I can work around this by using the non-v6 button, but non-v6 forces an 18px width and height on the icon. A CSS selector targeting the SVG or a `span` wrapping the SVG works around the 18px dimension problem. I'd love to instead avoid custom styles or wrapper hacks and use a disabled v6 `Button`.

**Comment by bryanrsmith** [comment]
This behavior is by design. You can use the `css` prop, or wrap `Button` in a new styled component to customize styles applied to pseudo classes. More info in #386
