### ISSUE TITLE
[BUG] Cannot set v6 Button width or height via props

### ISSUE THREAD

**Issue by tywmick** [Faithlife/styled-ui#393]
### Describe the bug
When trying to use the `height` prop on a v6 `Button` (during #395), I discovered that Styled System's [layout utility](https://styled-system.com/table#layout) includes a shortcut prop called `size`, which sets both the `width` and `height` properties. The weird thing is that since the styles for `ButtonCore` [include both `sizeVariant` and `layout`](https://github.com/Faithlife/styled-ui/blob/eee81d8fdb743a47cfa32e727f41428cdcf264c4/components/button/Button.js#L70-L76), `Button`'s `size` prop sets both the size variant _and_ the CSS width and height. I would have thought that defining `size` as the prop name for a custom variant would override the layout utility's `size`, but apparently that isn't the case.

Anyway, since the default value of `ButtonCore`'s `size` prop is `'medium'`, this adds `width: medium; height: medium;` CSS to every default v6 `Button`. It also prevents setting `Button`'s width and height via `width` and `height` props—the `size` prop wins out here.

### To Reproduce
1. Use a v6 `Button`.
2. Try to use its `width` and `height` props.
3. Open the element inspector in the web dev tools in your browser.
4. Notice that the CSS `width` and `height` properties of the `button` in the DOM have the value `medium` (or another other value you passed to the `size` prop), not the values you passed to the `width` and `height` props.

### Expected behavior
The values passed to the `width` and `height` props should be reflected in the CSS in the browser.

### Screenshots
<img width="256" alt="Button CSS issues" src="https://user-images.githubusercontent.com/5317080/100522858-efdd6580-3179-11eb-9e85-bf0ffb3d724c.png">

### Desktop (please complete the following information):
- OS: macOS 10.15.7 (19H2)
- Browsers
  - Firefox 83.0 (64-bit)
  - Chromium 86.0.4240.193 (Official Build) (x86_64)
  - Safari 14.0 (15610.1.28.1.9, 15610)

### Additional context
I've opened an issue in Styled System (styled-system/styled-system#1728) to ask if this is a bug or if this behavior is intended, but in the meantime, I see two alternate ways of fixing this:

1. The alternative implemented in #394, creating a [custom style function](https://styled-system.com/api#system) that adds every `layout` prop except `size`, so `Button`'s `size` prop won't block its `width` and `height`.
2. Changing the name of the size variant prop to something else like `sizeVariant` instead of just `size`. This will probably break more people's current usage of the v6 `Button`, though.

**Comment by RobertBolender** [comment]
Excellent analysis, and I appreciate the link to the issue you opened in Styled System, I'll be watching for an answer there as well.
In the mean time, there is a workaround available by specifying both the `size` and the `width`/`height` props yourself, rather than relying on the default `size="medium"` prop. The `size` prop would have to be specified before the `width`/`height` props.

**Comment by tywmick** [comment]
@RobertBolender Sounds good! Should I start a PR to add a JSDoc comment to the v6 `Button` detailing that workaround, or is that just a short term thing till we hear back from Styled System, so I shouldn't bother?

**Comment by RobertBolender** [comment]
@tywmick Adding a comment to the v6 Button component sounds like a good idea to me, I'd merge that PR 👍

**Comment by RobertBolender** [comment]
I believe this has been fully resolved by #398, if that is not the case, please feel free to re-open the issue.
