### ISSUE TITLE
[RFD] ImageWell

### ISSUE THREAD

**Issue by zachsnoek** [Faithlife/styled-ui#431]
# ImageWell

* Specifically describe the problem you'd like the new component to solve:

There are a couple of instances of an "image well" (or "image selector") component. When clicked, the component will launch an AssetPicker and display a preview of the selected image. The component is not being exported from a shared library, so the styles are being copied across different projects. We would like to add this to `tv-management` but don't want to duplicate the component again.

* Describe the proposed API:

```js
ImageWell.propTypes = {
  size: PropTypes.string,
  onClick: PropTypes.function,
  disabled: PropTypes.boolean,
  previewUrl: PropTypes.string,
  fitOverlayToSquare: PropTypes.boolean,
}
```

Example usage:

This would show the default "+ Add Image" text and camera icon that are shown if there is no `previewUrl`.

```jsx
const handleClick = async () => {
  const image = await pickImage();
  setSelectedImage(image);
}

<ImageWell
  onClick={handleClick}
  previewUrl={selectedImage?.url}
/>
```

The default content shown when `previewUrl` is not specified can be changed by providing children.

```jsx
const handleClick = async () => {
  const roomLayout = await pickRoomLayout();
  setSelectedLayout(roomLayout);
}

<ImageWell
  size="small"
  onClick={handleClick}
  previewUrl={selectedLayout?.url}
>
  <RoomIcon />
  {"+ Add room layout"}
</ImageWell>
```

* Are there existing specs or designs?

    * [ChurchManagement](https://git.faithlife.dev/Logos/ChurchManagement/blob/master/chms-tool/src/components/EditRecordWizard/FormComponents/Image/ImageSelector.tsx)
    * [ProclaimDigitalSignage](https://git.faithlife.dev/Logos/ProclaimDigitalSignage/blob/master/src/components/signage-faithlife-tab/image-picker/index.jsx)

No preview image specified:

![Screen Shot 2021-01-08 at 9 47 55 AM](https://user-images.githubusercontent.com/26049962/104047949-58ffc200-5197-11eb-9fc8-44927f1bfa97.png)

Preview image specified:

![Screen Shot 2021-01-08 at 9 48 55 AM](https://user-images.githubusercontent.com/26049962/104047964-5e5d0c80-5197-11eb-91f1-b4f3d57ce591.png)

**Comment by RobertBolender** [comment]
Excellent write-up 👍 
This looks like a great candidate for Styled-UI.
A couple of notes:
1. This component should definitely not have any dependency on the AssetPicker, that would be up to the consumer to supply
2. We either need to have a solution for handling localization in this component, or else force the consumer to supply that as well. This conversation is also relevant to the Toggle component: https://github.com/Faithlife/styled-ui/issues/145

**Comment by RobertBolender** [comment]
@zachsnoek is there a Zeplin spec for this component that indicates all of its measurements and hover/active states?

**Comment by zachsnoek** [comment]
> @zachsnoek is there a Zeplin spec for this component that indicates all of its measurements and hover/active states?

There is potentially a spec for this component in [ChurchManagement #7](https://git.faithlife.dev/Logos/ChurchManagement/pull/7#issue-30759) (I'm currently working on getting Zeplin access so I can't confirm that this is the spec or not).

**Comment by RobertBolender** [comment]
I was able to get an updated design spec here (for once you have access to Zeplin):
https://app.zeplin.io/project/58a23c2d4597afb248c13a43/screen/5e3df559213d160ea3f0db3e

**Comment by forresthopkinsa** [comment]
tv-management UI specs want these ImageWell elements to be drag-and-drop friendly, as in the attached image. Do you guys think this is a practical extension of the existing component?

![image](https://user-images.githubusercontent.com/4433153/119024315-c991c900-b957-11eb-8274-68ae979db1f5.png)

**Comment by RobertBolender** [comment]
@forresthopkinsa would either of these components fit your use case?
https://faithlife.github.io/styled-ui/#/files-section/variations
https://faithlife.github.io/styled-ui/#/drop-zone/variations

If not, please open a new issue with links to your relevant specs 👍

**Comment by forresthopkinsa** [comment]
Yeah, the drag-and-drop functionality of those is what I'm looking for, but the ImageWell's more specific use case (attaching images and showing a preview) is what we need. As far as I understand, the ImageWell component was introduced specifically for use with tv-management / live stream, so this probably doesn't call for a new component, right?

I can open a new issue to track the addition of drag/drop functionality to the ImageWell component if you think that's appropriate.

**Comment by RobertBolender** [comment]
That sounds great, thanks for the new issue 👍
