### ISSUE TITLE
Console errors when using ModalFooterButtons

### ISSUE THREAD

**Issue by KatieBorley** [Faithlife/styled-ui#509]
<img width="1026" alt="Screen Shot 2021-09-07 at 1 52 27 PM" src="https://user-images.githubusercontent.com/90289507/132419466-91cf70c6-43b9-45d6-b47e-c3ae4b0202e9.png">
These errors appear in the console when opening a Modal that contains a ModalFooterButtons component. Other than the messages appearing, it doesn't seem to affect functionality. 

I believe the errors are because [the Button component expects the size prop to be oneOf small, medium, or large](https://github.com/Faithlife/styled-ui/blob/master/components/button/Button.js#L93), but [the ModalFooterButtons component passes in an array containing small and medium](https://github.com/Faithlife/styled-ui/blob/master/components/modal/modal-footer-buttons.jsx#L23).

**Comment by korbinancell** [comment]
Thanks for the issue.

Note for fixer: Looks like there are a few prop types issues with styled-ui a couple more are listed here: https://git.faithlife.dev/Logos/Giving.Web/blob/1cda73b038ade704285e52ebfcb361bb766146d3/packages/test-utils/setup.js#L12
