### ISSUE TITLE
Server rendering fails due to undefined window variable

### ISSUE THREAD

**Issue by JeremyEinfeld** [Faithlife/styled-ui#69]
The error happens within the `react-scrollbar` module, here's an issue at that project's repository that describes the error that is seen: https://github.com/souhe/reactScrollbar/issues/70.

The error that I am seeing locally:
```
[ReactScriptLoadException: Error while loading "~/Scripts/dist/server/components-bundle.js": ReferenceError: 'window' is not defined
   at Anonymous function (eval code:2:12699) -> …t&&(t=e.apply(this,arguments)),t}},y=h(function(){return/msie [6-9]\b/.test(window.navigator.userA…
```

**Comment by JordanSjodinFaithlife** [comment]
hmm. I thought I was loading this module in 'componentDidMount' to prevent this but looks like I'm not.. I will take a look

**Comment by EthanRutherford** [comment]
Do we have an ETA on a fix?

**Comment by dustinsoftware** [comment]
If @JordanSjodinFaithlife can't get to it tomorrow, I'll back out the react-scrollbar module until he is available :)

**Comment by JordanSjodinFaithlife** [comment]
I'm ready to do it tomorrow for sure!

**Comment by EthanRutherford** [comment]
Thanks!

**Comment by JordanSjodinFaithlife** [comment]
Addressed here: https://github.com/Faithlife/styled-ui/pull/73

let me know what you think

**Comment by dustinsoftware** [comment]
This is resolved now.
