### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by dustinsoftware** [Faithlife/styled-ui#97]
Draft changelog

* **Important**: If you were using the brand new `Input` controls, the height of `small`, `medium`, and `large` has been adjusted to match `Button` variations. Please make sure your UI still renders properly!
* **New component**: `InferredSelect`, which uses the new `react-select` control. #93 #95 
* **New component**: `DatePeriodPicker` #91 
* **Deprecated**: `InferredTypeahead` is now deprecated in favor of `InferredSelect`, please migrate your code (chms should be the only tool using this)
* Fix group creation for in place group selector (#94) 
* Use new tooltip in inferred controls (a096de5394d1df6d1777fd5ef340e633389c09b9)
* Prevent popover arrow from interfering with mouse events (#92)

**Comment by awesomebob** [comment]
Closed via c1cd66f242dc3e0ecfda813597f5e35fb4617a65
